### ISSUE TITLE
RollupError

### ISSUE THREAD

**Issue by austinarchibald** [LizardByte/homebrew-homebrew#15]
### Describe the Bug

Was having some issues with sunshine not working, so wanted to uninstall/reinstall. Successfully uninstalled and untapped. But then I got an error after running `brew install sunshine`.

```
==> Installing sunshine from lizardbyte/homebrew
==> cmake -S . -B build -DBUILD_WERROR=ON -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/o
==> make -j
Last 15 lines from /Users/austin/Library/Logs/Homebrew/sunshine/02.make:
✓ built in 777ms
error during build:
RollupError: The "fileName" or "name" properties of emitted chunks and assets must be strings that are neither absolute nor relative paths, received "../../../../../../private/tmp/sunshine-20240527-47730-vdwf2r/src_assets/common/assets/web/apps.html".
    at error (file:///private/tmp/sunshine-20240527-47730-vdwf2r/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at FileEmitter.emitFile (file:///private/tmp/sunshine-20240527-47730-vdwf2r/node_modules/rollup/dist/es/shared/node-entry.js:25039:24)
    at Object.generateBundle (file:///private/tmp/sunshine-20240527-47730-vdwf2r/node_modules/vite/dist/node/chunks/dep-52909643.js:37929:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bundle.generate (file:///private/tmp/sunshine-20240527-47730-vdwf2r/node_modules/rollup/dist/es/shared/node-entry.js:17930:9)
    at async file:///private/tmp/sunshine-20240527-47730-vdwf2r/node_modules/rollup/dist/es/shared/node-entry.js:26785:27
    at async catchUnfinishedHookActions (file:///private/tmp/sunshine-20240527-47730-vdwf2r/node_modules/rollup/dist/es/shared/node-entry.js:25910:16)
    at async build (file:///private/tmp/sunshine-20240527-47730-vdwf2r/node_modules/vite/dist/node/chunks/dep-52909643.js:48085:22)
    at async CAC.<anonymous> (file:///private/tmp/sunshine-20240527-47730-vdwf2r/node_modules/vite/dist/node/cli.js:842:9)
make[2]: *** [CMakeFiles/web-ui] Error 1
make[1]: *** [CMakeFiles/web-ui.dir/all] Error 2
make: *** [all] Error 2
```

Am I on wrong version?

```
==> Checking out tag master
Already on 'master'
HEAD is now at c63637f Merge pull request #1756 from LizardByte/nightly
```

**Comment by ReenigneArcher** [comment]
Probably related to us renaming some branches. i.e. `nightly` became `master` and `master` became `master_legacy`.

**Comment by Nordln** [comment]
I have a similar issue here with the git branch naming:

```
~ % brew install lizardbyte/homebrew/sunshine
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/services).
No changes to formulae or casks.

==> Fetching lizardbyte/home brew/sunshine
==> Cloning https://github.com/LizardByte/Sunshine.git
Updating /Users/user1/Library/Caches/Homebrew/sunshine--git
fatal: couldn't find remote ref refs/tags/master
Error: sunshine: Failed to download resource "sunshine"
Failure while executing; `/usr/bin/env git fetch origin` exited with 128. Here's the output:
fatal: couldn't find remote ref refs/tags/master 

~ % 
```

**Comment by Nordln** [comment]
Update: Removing directory 'sunshine--git' from /Users/user1/Library/Caches/Homebrew/ allowed the build to complete.

**Comment by austinarchibald** [comment]
> Update: Removing directory 'sunshine--git' from /Users/user1/Library/Caches/Homebrew/ allowed the build to complete.

Thank you! This also allowed me to complete the brew install. Also, for anyone having issues starting, I had to run `brew services restart sunshine` instead of `start` which yielded an error. All working now, thanks!

**Comment by ReenigneArcher** [comment]
Should be able to do this to remove brew cache before installing new versions. https://github.com/LizardByte/Sunshine/issues/2369#issuecomment-2110532333

**Comment by ReenigneArcher** [comment]
I'm disabling issues in this repo. You can report any issues to the parent project, i.e. Sunshine in this case.
